---
# file: nginx/tasks/main.yml

- name: Ensure git is installed
  apt: name=git state=present
  tags:
    - pepyatka
    - nginx

- name: Install jake
  command: npm install --global jake
  tags:
    - pepyatka
    - nginx

- include: ember.yml
  when: pepyatka_html_enabled
  tags:
    - ember
    - pepyatka
    - nginx

- include: react.yml
  when: freefeed_react_client_enabled
  tags:
    - freefeed_react_client
    - pepyatka
    - nginx

- include: pepyatka-lite.yml
  when: pepyatka_lite_enabled
  tags:
    - pepyatka-lite

- name: Add apt key for the nginx repository
  apt_key: url="http://nginx.org/keys/nginx_signing.key" state=present
  tags:
    - redis

- name: Add nginx apt repository
  apt_repository: repo="deb http://nginx.org/packages/debian/ {{ ansible_lsb.codename }} nginx"
  tags:
    - pepyatka
    - nginx

- name: Install nginx
  apt: name=nginx state=present update_cache=yes force=yes
  tags:
    - pepyatka
    - nginx

- name: Deploy custom logrotate config for nginx
  copy: src=logrotate_d_nginx dest=/etc/logrotate.d/nginx
  tags:
    - pepyatka
    - nginx

- name: Ensure /etc/nginx/ssl
  file: path=/etc/nginx/ssl state=directory
  tags:
    - pepyatka
    - nginx

- name: Deploy server certificate
  copy:
    content="{{ server_cert }}"
    dest=/etc/nginx/ssl/api.pepyatka.crt
    mode=0600
  when: server_cert is defined
  tags:
    - pepyatka
    - nginx

- name: Deploy server certificate key
  copy:
    content="{{ server_cert_key }}"
    dest=/etc/nginx/ssl/api.pepyatka.key
    mode=0600
  when: server_cert_key is defined
  tags:
    - pepyatka
    - nginx

- name: Ensure nginx has access to pepyatka files
  file:
    path: "{{ pepyatka_files_dir }}"
    group: "{{ www_group }}"
    state: directory
    recurse: yes
    mode: 0775
  tags:
    - pepyatka
    - nginx

- name: Deploy nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  tags:
    - pepyatka
    - nginx
    - nginx-config

- name: Deploy nginx common config
  template: src=pepyatka-common.conf.j2 dest=/etc/nginx/pepyatka-common.conf
  tags:
    - pepyatka
    - nginx
    - nginx-config

- name: Deploy nginx shared config
  template: src=pepyatka-shared.conf.j2 dest=/etc/nginx/pepyatka-shared.conf
  tags:
    - pepyatka
    - nginx
    - nginx-config

- name: Deploy nginx ssl config
  template: src=pepyatka-ssl.conf.j2 dest=/etc/nginx/pepyatka-ssl.conf
  tags:
    - pepyatka
    - nginx
    - nginx-config

- name: Deploy dhparams.pem
  copy: content="{{ nginx_ssl_dhparam }}" dest=/etc/ssl/dhparams.pem
  when: nginx_ssl_dhparam is defined
  tags:
    - pepyatka
    - nginx
    - nginx-config

- name: Start and enable nginx
  service: name=nginx state=started enabled=yes
  tags:
    - pepyatka
    - nginx
    - nginx-config

- name: Reload nginx config
  command: /etc/init.d/nginx reload
  tags:
    - pepyatka
    - nginx
    - nginx-config

- name: Ensure nginx is up and running
  wait_for: host=localhost port={{ server_cert is defined | ternary(443, 80) }} timeout=30 state=started
  tags:
    - pepyatka
    - nginx
    - nginx-config

